import subprocess
from rich import print
from typing import Dict, Any

def install_python_package(package: str) -> subprocess.CompletedProcess:
    """
    Installs a Python package using pip.
    Returns the subprocess.CompletedProcess object.
    """
    print(f"[cyan]Installing package:[/cyan] {package}")

    try:
        result = subprocess.run(
            ["python", "-m", "pip", "install", package],
            capture_output=True, # Capture output for observation
            text=True,           # Decode stdout/stderr as text
            check=False          # Do not raise CalledProcessError, return code will indicate failure
        )
        if result.returncode == 0:
            print("[green]Installation complete[/green]")
        else:
            print("[red]Installation failed[/red]")
            if result.stderr:
                print(f"[red]Error:[/red] {result.stderr}")
        return result
    except FileNotFoundError:
        # Handles cases where 'python' or 'pip' command might not be found
        error_msg = f"Error: 'python' or 'pip' command not found. Ensure Python is installed and in PATH."
        print(f"[red]{error_msg}[/red]")
        return subprocess.CompletedProcess(args=["python", "-m", "pip", "install", package], returncode=1, stdout="", stderr=error_msg)
    except Exception as e:
        # Catch other potential exceptions during subprocess execution
        error_msg = f"An unexpected error occurred during installation: {e}"
        print(f"[red]{error_msg}[/red]")
        return subprocess.CompletedProcess(args=["python", "-m", "pip", "install", package], returncode=1, stdout="", stderr=error_msg)


def run_action(plan_step: Dict[str, Any]) -> Any: # Returns an object compatible with observer.observe
    """
    Executes a given action based on the plan step.
    Returns a result object that can be passed to observer.observe.
    """
    action = plan_step.get("action")
    result = None # Initialize result to None

    if action == "install_package":
        package = plan_step.get("package")
        if package:
            print(f"[cyan]Running command:[/cyan] python -m pip install {package}")
            result = install_python_package(package)
        else:
            error_msg = f"Missing 'package' key for action 'install_package': {plan_step}"
            print(f"[red]{error_msg}[/red]")
            result = subprocess.CompletedProcess(args=[], returncode=1, stdout="", stderr=error_msg)

    elif action == "analyze_error":
        error_message = plan_step.get("error_message", "No error message provided.")
        stdout_msg = f"Analyzing error: {error_message}"
        print(f"[yellow]{stdout_msg}[/yellow]")
        # This action doesn't involve external command execution, so we create a dummy result.
        result = subprocess.CompletedProcess(args=[], returncode=0, stdout=stdout_msg, stderr="")

    elif action == "analyze_problem":
        problem_description = plan_step.get("problem_description", "No problem description provided.")
        stdout_msg = f"Analyzing problem: {problem_description}"
        print(f"[yellow]{stdout_msg}[/yellow]")
        result = subprocess.CompletedProcess(args=[], returncode=0, stdout=stdout_msg, stderr="")

    elif action == "retry_command":
        stdout_msg = "Retrying previous command."
        print(f"[yellow]{stdout_msg}[/yellow]")
        # This implies the agent loop itself should manage retrying the original command.
        # For this specific action, we return a success dummy result.
        result = subprocess.CompletedProcess(args=[], returncode=0, stdout=stdout_msg, stderr="")

    elif action == "suggest_manual_dependency_install":
        reason = plan_step.get("reason", "Unknown reason.")
        stdout_msg = f"Manual intervention suggested: Could not automatically determine package to install. Reason: {reason}"
        print(f"[yellow]{stdout_msg}[/yellow]")
        result = subprocess.CompletedProcess(args=[], returncode=0, stdout=stdout_msg, stderr="")

    # Keeping existing actions for completeness, though they might be generated by a more complex planner.
    elif action == "suggest_install_command":
        command = plan_step.get("command")
        stdout_msg = f"Suggested command: {command}"
        print(f"[yellow]You may need to install the command:[/yellow] {command}")
        result = subprocess.CompletedProcess(args=[], returncode=0, stdout=stdout_msg, stderr="")

    elif action == "suggest_run_with_sudo":
        stdout_msg = "Suggested: Try running with sudo."
        print("[yellow]Try running the command with sudo.[/yellow]")
        result = subprocess.CompletedProcess(args=[], returncode=0, stdout=stdout_msg, stderr="")

    elif action == "suggest_check_file_path":
        file = plan_step.get("file")
        stdout_msg = f"Suggested: Check file path: {file}"
        print(f"[yellow]Check if the file exists:[/yellow] {file}")
        result = subprocess.CompletedProcess(args=[], returncode=0, stdout=stdout_msg, stderr="")

    # If no action matched, return a default "no-op" result with an error
    if result is None:
        error_msg = f"Unknown or unhandled action: {action} in plan step: {plan_step}"
        print(f"[red]{error_msg}[/red]")
        result = subprocess.CompletedProcess(args=[], returncode=1, stdout="", stderr=error_msg)
        
    return result

